POST http://localhost:8080/v1/api/auth
Content-Type: application/json

{
    "fullName": "John Doe",
    "email": "john.doe@gmail.com",
    "password": "123456",
}


###

GET http://localhost:8080/v1/api/get-users

###

POST http://localhost:8080/v1/api/login
Content-Type: application/json

{
    "email": "rahul@gmail.com",
    "password": "123456"
}

###

POST http://localhost:8080/v1/api/register
Content-Type: application/json

{
    "name": "Rahul",
    "email": "rahul@gmail.com",
    "password": "123456",
    "age": 24
}
